
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from orthogonalrouting.enumerations.ConnectorOrientation import ConnectorOrientation
from orthogonalrouting.graph.interfaces.INode import INode

from orthogonalrouting.models.logicModels.Connector import Connector

from tests.orthogonalrouting.models.logicModels.InputItemV2 import InputItemV2


# import the class you want to test here
# from org.pyut.template import template


class TestConnector(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 18 March 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testCalculateOrientationNodeBottom(self):

        testInputItem: InputItemV2 = InputItemV2(x=200, y=100,
                                                 width=75, height=25,
                                                 right=300, bottom=200
                                                 )

        connector: Connector = Connector()

        node: INode = connector._calculateOrientationNode(orientation=ConnectorOrientation.BOTTOM, item=testInputItem)

        self.logger.info(f'{node=}')
        self.assertEqual(237, node.x, '')
        self.assertEqual(200, node.y, '')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestConnector))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
